name: Java CI with Maven for PR

on:
   pull_request: null

jobs:

   build:
   
      runs-on: ${{matrix.os}}
      
      strategy:
      
         matrix:
         
            os:
            - macos-latest
            - windows-latest
            
      name: Build Java 8 on ${{matrix.os}}
      
      steps:
      
      -  uses: actions/checkout@v2
      
      -  name: Set up JDK 8
         uses: actions/setup-java@v1
         with:
            java: 8

      -  name: Build with Maven
         run: maven -f myproject/pom.xml clen verify